// GENERATED by tools/calibrate.js — do not edit by hand.
//
// Measured draft price for every shipped species, in larvae. Each number is the
// point where fielding this unit instead of the ants it costs is a coin flip
// (see the tool for why measurement beats a formula here).
//
// Regenerate after changing unit stats, abilities, or the engine's combat maths:
//
//   npm run calibrate
//
// Species NOT listed here fall back to the stat-derived estimate in economy.js,
// so a newly added unit is playable immediately and can be calibrated later.
//
// Reference unit: Fire Ant = 5 larvae. Probes: 24 battles each.

export const CALIBRATED_COSTS = Object.freeze({
  "fireAnt": 5,
  "bulletAnt": 6,
  "suicideAnt": 4,
  "leafcutterAnt": 4,
  "armyAnt": 4,
  "trapjawAnt": 4,
  "honeypotAnt": 4,
  "workerAnt": 3,
  "carpenterAnt": 5,
  "crazyAnt": 5,
  "harvesterAnt": 4,
  "bulldogAnt": 5,
  "weaverAnt": 5,
  "amazonAnt": 5,
  "acrobatAnt": 6,
  "turtleAnt": 5,
  "draculaAnt": 5,
  "jackJumperAnt": 6,
  "pharaohAnt": 6,
  "thiefAnt": 5,
  "argentineAnt": 5,
  "zombieAnt": 5,
  "spider": 18,
  "mantis": 20,
  "scorpion": 8,
  "beetle": 38,
  "bombardier": 30,
  "hornet": 10,
  "centipede": 15,
  "queenAnt": 23,
  "assassinBug": 10,
  "spitter": 38,
  "widow": 13,
  "antlion": 43,
  "tarantulaHawk": 10,
  "waterBug": 18,
  "vinegaroon": 45,
  "goliathBeetle": 48,
  "dragonfly": 18,
  "jumpingSpider": 10,
  "velvetWorm": 28,
  "jewelWasp": 8,
  "coachHorse": 23,
  "solifuge": 15
});
